### ISSUE TITLE
Broken links on 5.1.2

### ISSUE THREAD

**Issue by amchagas** [rstudio-conf-2020/r-for-excel#3]
Hi!

Thanks for putting this excellent intro course together! 

I've been going through it and I noticed that the resource links on section 5.1.2 [here](https://rstudio-conf-2020.github.io/r-for-excel/ggplot2.html) are leading to a 404 page. No biggie, but thought a heads up would be useful :)

**Comment by allisonhorst** [comment]
Thank you for the catch @amchagas ! We've updated the resources links.
